/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smartgas;


import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrador
 */
public class telacliente extends javax.swing.JFrame {
ArrayList<cliente>  fichario = new ArrayList <cliente>();
cliente ficha =  new cliente();
int atual = 0;
int total =0;

    /**
     * Creates new form telacliente
     */
    public telacliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        entradanome = new javax.swing.JTextField();
        entradaendereco = new javax.swing.JTextField();
        entradatelefone = new javax.swing.JTextField();
        entradacidade = new javax.swing.JTextField();
        entradacpf = new javax.swing.JTextField();
        entradaemail = new javax.swing.JTextField();
        entradacep = new javax.swing.JTextField();
        Salva = new javax.swing.JButton();
        Anterior = new javax.swing.JButton();
        Proximo = new javax.swing.JButton();
        Cancela = new javax.swing.JButton();
        variavel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Endereço");

        jLabel3.setText("Telefone");

        jLabel4.setText("Cidade");

        jLabel5.setText("CPF");

        jLabel6.setText("Email");

        jLabel7.setText("CEP");

        entradaendereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entradaenderecoMouseClicked(evt);
            }
        });

        entradatelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entradatelefoneMouseClicked(evt);
            }
        });

        Salva.setText("Salvar");
        Salva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalvaMouseClicked(evt);
            }
        });

        Anterior.setText("Anterior");
        Anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnteriorMouseClicked(evt);
            }
        });

        Proximo.setText("Próximo");
        Proximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProximoMouseClicked(evt);
            }
        });

        Cancela.setText("Cancela");

        variavel.setText("0");

        jLabel8.setText("Registro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Salva)
                        .addGap(18, 18, 18)
                        .addComponent(Anterior)
                        .addGap(18, 18, 18)
                        .addComponent(Proximo)
                        .addGap(18, 18, 18)
                        .addComponent(Cancela))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(entradanome, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(entradaendereco)
                            .addComponent(entradacidade)
                            .addComponent(entradacpf, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradatelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradacep, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(entradaemail))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(variavel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entradanome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(entradaendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(entradatelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entradacpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entradaemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entradacep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(variavel)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salva)
                    .addComponent(Anterior)
                    .addComponent(Proximo)
                    .addComponent(Cancela))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvaMouseClicked
        // TODO add your handling code here:
        
        ficha= new cliente();        
        ficha.nome=entradanome.getText();
         entradanome.setText("");
                
        ficha.endereco=entradaendereco.getText();
        entradaendereco.setText("");        
       
        ficha.telefone=Integer.parseInt(entradatelefone.getText());
        entradatelefone.setText("");       
        
        ficha.cidade=entradacidade.getText();
        entradacidade.setText("");       
        
        ficha.CPF=Integer.parseInt(entradacpf.getText());
        entradacpf.setText(""); 
        
        
        ficha.email=entradaemail.getText();
        entradaemail.setText("");  
        
        ficha.cep=Integer.parseInt(entradacep.getText());
        entradacep.setText("");
        total++;
        atual = atual+1; //vai para a prox ficha
        variavel.setText(Integer.toString(atual));
        fichario.add(ficha);
        try {
            FileOutputStream arquivo = new FileOutputStream("clientes.ser");
            try {
                ObjectOutputStream salva = new  ObjectOutputStream (arquivo);
                salva.writeObject(fichario);
                salva.close();
                        
            } catch (IOException ex) {
                Logger.getLogger(telacliente.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
        } catch (FileNotFoundException ex) {
            Logger.getLogger(telacliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SalvaMouseClicked

    private void AnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnteriorMouseClicked
        // TODO add your handling code here:
        if (atual<=0){
            //avisa o usuario que chegou no inicio
            variavel.setText("Inicio atingido");
            atual=0;//volta para 0 para nao dar problema
        }else{
            atual = atual-1;//volta para a anterior 
            variavel.setText(Integer.toString(atual));
            //mostra qual o registro atual
        }
        ficha = new cliente();
        ficha = fichario.get(atual);// pega a ficha atual do fichario
        entradanome.setText(ficha.nome);
        entradaendereco.setText(ficha.endereco);
        entradatelefone.setText(Integer.toString(ficha.telefone));
        entradacidade.setText(ficha.cidade);
        entradacpf.setText(Integer.toString(ficha.CPF));
        entradacep.setText(Integer.toString(ficha.cep));
        entradaemail.setText(ficha.email);   
    }//GEN-LAST:event_AnteriorMouseClicked

    private void ProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProximoMouseClicked
        // TODO add your handling code here:
        if (atual>total){
            variavel.setText("Fim atingido!");
            atual=total;
        }else{
            atual=atual+1;
            variavel.setText(Integer.toString(atual));
        }
        
        entradanome.setText(ficha.nome);
        entradaendereco.setText(ficha.endereco);
        entradatelefone.setText(Integer.toString(ficha.telefone));
        entradacidade.setText(ficha.cidade);
        entradacpf.setText(Integer.toString(ficha.CPF));
        entradacep.setText(Integer.toString(ficha.cep));
        entradaemail.setText(ficha.email);
               
        
    }//GEN-LAST:event_ProximoMouseClicked

    private void entradaenderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradaenderecoMouseClicked
        // TODO add your handling code here:     
    }//GEN-LAST:event_entradaenderecoMouseClicked

    private void entradatelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradatelefoneMouseClicked
        // TODO add your handling code here:        
    }//GEN-LAST:event_entradatelefoneMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        File testa = new File ("cliente.ser");
        if (testa.exists()){
            try {
                FileInputStream arquivo = new FileInputStream("cliente.ser");
                ObjectInputStream carregar;
                try {
                    carregar = new ObjectInputStream(arquivo);
                    try {
                        Object objeto =  carregar.readObject();
                        fichario = (ArrayList<cliente>) objeto;
                        carregar.close();
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(telacliente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                } catch (IOException ex) {
                    Logger.getLogger(telacliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(telacliente.class.getName()).log(Level.SEVERE, null, ex);
            }
                

                total = fichario.size();
                atual = total-1;
                ficha = new cliente();
                ficha = fichario.get(atual);// pega a ficha atual do fichario
                entradanome.setText(ficha.nome);
                entradaendereco.setText(ficha.endereco);
                entradatelefone.setText(Integer.toString(ficha.telefone));
                entradacidade.setText(ficha.cidade);
                entradacpf.setText(Integer.toString(ficha.CPF));
                entradacep.setText(Integer.toString(ficha.cep));
                entradaemail.setText(ficha.email);   

        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telacliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telacliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telacliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telacliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new telacliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior;
    private javax.swing.JButton Cancela;
    private javax.swing.JButton Proximo;
    private javax.swing.JButton Salva;
    private javax.swing.JTextField entradacep;
    private javax.swing.JTextField entradacidade;
    private javax.swing.JTextField entradacpf;
    private javax.swing.JTextField entradaemail;
    private javax.swing.JTextField entradaendereco;
    private javax.swing.JTextField entradanome;
    private javax.swing.JTextField entradatelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel variavel;
    // End of variables declaration//GEN-END:variables
}
