/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smartgas;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class telavenda extends javax.swing.JFrame {
ArrayList <cliente> fichas_cliente = new ArrayList<cliente>();
    ArrayList <Funcionario> fichas_funcionario = new ArrayList<Funcionario>();
    ArrayList <produto> fichas_produto = new ArrayList<produto>();
    ArrayList <venda> fichas_venda = new ArrayList<venda>();
    ArrayList <itens_venda> fichas_item = new ArrayList<itens_venda>();
    
    venda ficha_venda = new venda();
    itens_venda ficha_item = new itens_venda();
    produto fichaP = new produto();
    float totalvenda = 0;
    /**
     * Creates new form telavenda
     */
    public telavenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboF = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        entradaquantidade = new javax.swing.JTextField();
        entradavalorcompra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        incluir = new javax.swing.JButton();
        ComboP = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        qtde_estoque = new javax.swing.JLabel();
        itensvenda = new javax.swing.JScrollPane();
        tabelaitens = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        ComboC = new javax.swing.JComboBox();
        finalizarvenda = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Funcionario:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Produto:");

        jLabel3.setText("Quantidade:");

        jLabel4.setText("Valor de compra:");

        incluir.setText("Incluir");
        incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirActionPerformed(evt);
            }
        });

        ComboP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantidade em estoque:");

        qtde_estoque.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(entradaquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(ComboP, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradavalorcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtde_estoque)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(qtde_estoque))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entradaquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entradavalorcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tabelaitens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Valor de Compra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itensvenda.setViewportView(tabelaitens);

        jLabel5.setText("Cliente:");

        finalizarvenda.setText("Finalizar venda");
        finalizarvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarvendaActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("R$");

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(finalizarvenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelar)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itensvenda, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboC, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboF, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ComboC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itensvenda, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6))
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalizarvenda)
                    .addComponent(cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            ObjectInputStream arqEntrada = new ObjectInputStream(new FileInputStream(new File("cliente.ser")));
            fichas_cliente = (ArrayList<cliente>) arqEntrada.readObject();
            int totalF = fichas_cliente.size();
            for (int x=0; x<totalF;x++){ //for
                ComboC.addItem(fichas_cliente.get(x).nome);
            }
        }
        catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, "Arquivo não encontrado Cliente", "SmartGas", JOptionPane.ERROR_MESSAGE);
        }
        catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(null, "Erro na abertura do arquivo de dados Cliente", "SmartGas", JOptionPane.ERROR_MESSAGE);
        }
        catch(IOException e){
                   JOptionPane.showMessageDialog(null, "Erro na leitura dos dados Cliente", "SmartGas", JOptionPane.ERROR_MESSAGE);
        }
        //Funcionario
        try{
            ObjectInputStream arqEntrada = new ObjectInputStream(new FileInputStream(new File("funcionario.ser")));
            fichas_funcionario = (ArrayList<Funcionario>) arqEntrada.readObject();
            int totalF = fichas_funcionario.size();
            for (int x=0; x<totalF;x++){ //for
                ComboF.addItem(fichas_funcionario.get(x).nome);
            }
        }
        catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, "Arquivo não encontrado Funcionario", "SmartGas", JOptionPane.ERROR_MESSAGE);
        }
        catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(null, "Erro na abertura do arquivo de dados Funcionario", "SmartGas", JOptionPane.ERROR_MESSAGE);
        }
        catch(IOException e){
                   JOptionPane.showMessageDialog(null, "Erro na leitura dos dados Funcionario", "SmartGas", JOptionPane.ERROR_MESSAGE);
        } 
        //Produto
        try{
            ObjectInputStream arqEntrada = new ObjectInputStream(new FileInputStream(new File("produto.ser")));
            fichas_produto = (ArrayList<produto>) arqEntrada.readObject();
            int totalP = fichas_produto.size();
            for (int x=0; x<totalP;x++){ //for
            ComboP.addItem(fichas_produto.get(x).tipo);
            }
        }
        catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, "Arquivo não encontrado produto", "SmartGas", JOptionPane.ERROR_MESSAGE);
        }
        catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(null, "Erro na abertura do arquivo de dados produto", "SmartGas", JOptionPane.ERROR_MESSAGE);
        }
        catch(IOException e){
                   JOptionPane.showMessageDialog(null, "Erro na leitura dos dados produto", "SmartGas", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened

    private void incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirActionPerformed
        // TODO add your handling code here:
       
        if (fichaP.quantidade>=Integer.parseInt(entradaquantidade.getText()))
        {
        Object linha[] = {ComboP.getSelectedItem(),entradaquantidade.getText(),entradavalorcompra.getText()};
        DefaultTableModel dtm = (DefaultTableModel) tabelaitens.getModel();
        dtm.addRow(linha);
        
        //inclui um item de venda
        ficha_item.cod_produto = ComboP.getSelectedItem().hashCode();
        ficha_item.cod_venda = ficha_venda.hashCode();
        ficha_item.preco_venda = Float.parseFloat(entradavalorcompra.getText());
        ficha_item.quantidade = Integer.parseInt(entradaquantidade.getText());
        fichas_item.add(ficha_item);
        
        //altera o estoque do produto
        int indice = ComboP.getSelectedIndex();
        fichaP = fichas_produto.get(indice);
        fichaP.quantidade = fichaP.quantidade-ficha_item.quantidade;
        fichas_produto.set(indice, fichaP);
        
        //Calcula o valor Total
        totalvenda = (Float.parseFloat(entradaquantidade.getText().toString()) * Float.parseFloat(entradavalorcompra.getText()))+totalvenda;
        jTextFieldTotal.setText(Float.toString(totalvenda));
        
        //limpa os campos
        entradaquantidade.setText("");
        entradavalorcompra.setText("");
        ComboPActionPerformed(evt);
        }
        else
        {
          JOptionPane.showMessageDialog(null, "Quantidade insuficiente de produtos no estoque", "SmartGas", JOptionPane.ERROR_MESSAGE);  
          jTextFieldTotal.setText("");
        }
    }//GEN-LAST:event_incluirActionPerformed

    private void finalizarvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarvendaActionPerformed
          //salva a venda
          ficha_venda.cod_cliente=ComboC.getSelectedItem().hashCode();
          ficha_venda.cod_funcionario = ComboF.getSelectedItem().hashCode();
          ficha_venda.data_venda = new Date();
          ficha_venda.valor_total = totalvenda;
          ficha_venda.itensVenda = fichas_item;
      
          fichas_venda.add(ficha_venda);
          try {
            FileOutputStream  arquivo = new FileOutputStream("venda.ser");
           try {
                ObjectOutputStream salva = new  ObjectOutputStream (arquivo);
                salva.writeObject(fichas_venda);
                salva.close();
            } catch (IOException ex) {
                Logger.getLogger(telaproduto.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(telaproduto.class.getName()).log(Level.SEVERE, null, ex);
        }
          
          FileOutputStream filestream;
        try {
            filestream = new FileOutputStream("produto.ser");
            try {
                ObjectOutputStream arquivo = new ObjectOutputStream(filestream);
                arquivo.writeObject(fichas_produto);
                arquivo.close();
            } catch (IOException ex) {
                Logger.getLogger(Telafornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Telafornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
          this.dispose();
               // TODO add your handling code here:
    }//GEN-LAST:event_finalizarvendaActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
         if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Fechar?","atenção ",javax.swing.JOptionPane.YES_NO_OPTION )==0){  
                this.dispose();  }
    }//GEN-LAST:event_cancelarActionPerformed

    private void ComboPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPActionPerformed
        // TODO add your handling code here:
        //Pega a Quantidade em estoque
        fichaP = fichas_produto.get(ComboP.getSelectedIndex());
        qtde_estoque.setText(Integer.toString(fichaP.quantidade));
    }//GEN-LAST:event_ComboPActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telavenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telavenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telavenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telavenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new telavenda().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboC;
    private javax.swing.JComboBox ComboF;
    private javax.swing.JComboBox ComboP;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField entradaquantidade;
    private javax.swing.JTextField entradavalorcompra;
    private javax.swing.JButton finalizarvenda;
    private javax.swing.JButton incluir;
    private javax.swing.JScrollPane itensvenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JLabel qtde_estoque;
    private javax.swing.JTable tabelaitens;
    // End of variables declaration//GEN-END:variables
}
