/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smartgas;

/**
 *
 * @author Usuario
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
       this.setExtendedState(MAXIMIZED_BOTH);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelprincipal = new javax.swing.JPanel();
        Venda = new javax.swing.JButton();
        Compra = new javax.swing.JButton();
        cadastro = new javax.swing.JButton();
        relatorios = new javax.swing.JButton();
        painelcadastro = new javax.swing.JPanel();
        CadastroFornecedor = new javax.swing.JButton();
        CadastroFuncionario = new javax.swing.JButton();
        CadastroProduto = new javax.swing.JButton();
        CadastroCliente = new javax.swing.JButton();
        painelrelatorio = new javax.swing.JPanel();
        relatorioestoque = new javax.swing.JButton();
        relatoriovenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        painelprincipal.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        painelprincipal.setLayout(new java.awt.GridLayout(4, 0));

        Venda.setText("Venda");
        Venda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VendaMouseClicked(evt);
            }
        });
        painelprincipal.add(Venda);

        Compra.setText("Compra");
        Compra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompraMouseClicked(evt);
            }
        });
        painelprincipal.add(Compra);

        cadastro.setText("cadastros");
        cadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroMouseClicked(evt);
            }
        });
        painelprincipal.add(cadastro);

        relatorios.setText("relatorios");
        relatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relatoriosMouseClicked(evt);
            }
        });
        relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatoriosActionPerformed(evt);
            }
        });
        painelprincipal.add(relatorios);

        painelcadastro.setBorder(new javax.swing.border.MatteBorder(null));
        painelcadastro.setLayout(new java.awt.GridLayout(4, 0));

        CadastroFornecedor.setText("Cadastro Fornecedor");
        CadastroFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastroFornecedorMouseClicked(evt);
            }
        });
        painelcadastro.add(CadastroFornecedor);

        CadastroFuncionario.setText("Cadastro Funcionario");
        CadastroFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastroFuncionarioMouseClicked(evt);
            }
        });
        painelcadastro.add(CadastroFuncionario);

        CadastroProduto.setText("Cadastro Produto");
        CadastroProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastroProdutoMouseClicked(evt);
            }
        });
        CadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroProdutoActionPerformed(evt);
            }
        });
        painelcadastro.add(CadastroProduto);

        CadastroCliente.setText("Cadastro Cliente");
        CadastroCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastroClienteMouseClicked(evt);
            }
        });
        CadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroClienteActionPerformed(evt);
            }
        });
        painelcadastro.add(CadastroCliente);

        painelrelatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelrelatorio.setLayout(new java.awt.GridLayout());

        relatorioestoque.setText(" relatorio estoque");
        relatorioestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioestoqueActionPerformed(evt);
            }
        });
        painelrelatorio.add(relatorioestoque);

        relatoriovenda.setText("relatorio venda");
        relatoriovenda.setAlignmentX(0.6F);
        painelrelatorio.add(relatoriovenda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelrelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelrelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelcadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastroFornecedorMouseClicked
        // TODO add your handling code here:
        new Telafornecedor().setVisible(true);
        
    }//GEN-LAST:event_CadastroFornecedorMouseClicked

    private void CadastroClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastroClienteMouseClicked
        // TODO add your handling code here:
        new telacliente().setVisible(true);
    }//GEN-LAST:event_CadastroClienteMouseClicked

    private void CompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompraMouseClicked
        // TODO add your handling code here:
        new telacompra().setVisible(true);
    }//GEN-LAST:event_CompraMouseClicked

    private void CadastroFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastroFuncionarioMouseClicked
        // TODO add your handling code here:
        new TelaFuncionario().setVisible(true);
    }//GEN-LAST:event_CadastroFuncionarioMouseClicked

    private void CadastroProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastroProdutoMouseClicked
        // TODO add your handling code here:
        new telaproduto().setVisible(true);
    }//GEN-LAST:event_CadastroProdutoMouseClicked

    private void VendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VendaMouseClicked
        // TODO add your handling code here:
        new telavenda().setVisible(true);
    }//GEN-LAST:event_VendaMouseClicked

    private void CadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroClienteActionPerformed

    private void CadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroProdutoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CadastroProdutoActionPerformed

    private void relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relatoriosActionPerformed

    private void cadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroMouseClicked
        // TODO add your handling code here:
         painelcadastro.setVisible(true);
    }//GEN-LAST:event_cadastroMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        painelcadastro.setVisible(false);
        painelrelatorio.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void relatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relatoriosMouseClicked
        // TODO add your handling code here:
         painelrelatorio.setVisible(true);
    }//GEN-LAST:event_relatoriosMouseClicked

    private void relatorioestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioestoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relatorioestoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroCliente;
    private javax.swing.JButton CadastroFornecedor;
    private javax.swing.JButton CadastroFuncionario;
    private javax.swing.JButton CadastroProduto;
    private javax.swing.JButton Compra;
    private javax.swing.JButton Venda;
    private javax.swing.JButton cadastro;
    private javax.swing.JPanel painelcadastro;
    private javax.swing.JPanel painelprincipal;
    private javax.swing.JPanel painelrelatorio;
    private javax.swing.JButton relatorioestoque;
    private javax.swing.JButton relatorios;
    private javax.swing.JButton relatoriovenda;
    // End of variables declaration//GEN-END:variables
}
