/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smartgas;

import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrador
 */
public class Telafornecedor extends javax.swing.JFrame {
fornecedor ficha  = new fornecedor();
ArrayList<fornecedor>  fichario = new ArrayList<fornecedor>();
int atual = 0;// controla a ficha atual
int total =0;//conta o total de fichas criadas

    /**
     * Creates new form telafornecedor
     */
    public Telafornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        entradanome = new javax.swing.JTextField();
        entradaendereco = new javax.swing.JTextField();
        entradatelefone = new javax.swing.JTextField();
        entradacidade = new javax.swing.JTextField();
        Salvar = new javax.swing.JButton();
        Anterior = new javax.swing.JButton();
        Proximo = new javax.swing.JButton();
        Cancela = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        contador = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Endereço");

        jLabel3.setText("Telefone");

        jLabel4.setText("Cidade");

        entradanome.setPreferredSize(new java.awt.Dimension(180, 28));

        entradaendereco.setPreferredSize(new java.awt.Dimension(180, 28));

        entradatelefone.setPreferredSize(new java.awt.Dimension(180, 28));

        entradacidade.setPreferredSize(new java.awt.Dimension(180, 28));

        Salvar.setText("Salvar");
        Salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalvarMouseClicked(evt);
            }
        });

        Anterior.setText("Anterior");
        Anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnteriorMouseClicked(evt);
            }
        });

        Proximo.setText("Próximo");
        Proximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProximoMouseClicked(evt);
            }
        });

        Cancela.setText("Cancela");

        jLabel5.setText("Registro atual:");

        contador.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(entradacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(entradatelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(entradaendereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(entradanome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(contador))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Salvar)
                        .addGap(18, 18, 18)
                        .addComponent(Anterior)
                        .addGap(18, 18, 18)
                        .addComponent(Proximo)
                        .addGap(18, 18, 18)
                        .addComponent(Cancela)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(entradanome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(entradaendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(entradatelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(entradacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(contador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salvar)
                    .addComponent(Anterior)
                    .addComponent(Proximo)
                    .addComponent(Cancela))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseClicked
        ficha  = new fornecedor();       
        ficha.nome = entradanome.getText();
        ficha.endereco = entradaendereco.getText();
        ficha.telefone = Integer.parseInt(entradatelefone.getText());
        ficha.cidade = entradacidade.getText();
        //acabou a coleta de dados
        //Limpa os campos
        entradanome.setText("");
        entradaendereco.setText("");
        entradatelefone.setText("");
        entradacidade.setText("");
        //limpando os campos
        
        //atualiza o contador
        atual++;// faz a mesma coisa que atual=atual+1
        //mostra em qual registro está(registro atual)
        contador.setText(Integer.toString(atual));
        fichario.add(ficha);
        FileOutputStream filestream;
        try {
            filestream = new FileOutputStream("fornecedor.ser");
            try {
                ObjectOutputStream arquivo = new ObjectOutputStream(filestream);
                arquivo.writeObject(fichario);
                arquivo.close();
            } catch (IOException ex) {
                Logger.getLogger(Telafornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Telafornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        
    }//GEN-LAST:event_SalvarMouseClicked

    private void AnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnteriorMouseClicked
        // TODO add your handling code here:
        // 0 1 2 3 4 5 6 7 8 9
        if (atual<=0){
            atual=0;
        }else{
            atual--;
            
        }
        contador.setText(Integer.toString(atual));
        ficha = fichario.get(atual);
        entradanome.setText(ficha.nome);
        entradaendereco.setText(ficha.endereco);
        entradatelefone.setText(Integer.toString(ficha.telefone));
        entradacidade.setText(ficha.cidade);
    }//GEN-LAST:event_AnteriorMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     File teste = new File("fornecedor.ser"); 
     if (teste.exists()){
            try {
                FileInputStream arquivo = new FileInputStream("fornecedor.ser");
                try {
                    ObjectInputStream fluxo = new ObjectInputStream (arquivo);
                    try {
                     Object objeto = fluxo.readObject();
                     fichario = (ArrayList<fornecedor>) objeto ;
                     total = fichario.size();
                     atual = total -1;
                     ficha = fichario.get(atual);
                     entradanome.setText(ficha.nome);
                     entradaendereco.setText(ficha.endereco);
                     entradatelefone.setText(Integer.toString(ficha.telefone));
                     entradacidade.setText(ficha.cidade);
                     contador.setText(Integer.toString(atual));
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Telafornecedor.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Telafornecedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Telafornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }
     }
         
    }//GEN-LAST:event_formWindowOpened

    private void ProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProximoMouseClicked
        // TODO add your handling code here:
        if  (atual >=total-1){
            atual = total-1 ;
        } 
        else {
            atual++;
        }
        contador.setText(Integer.toString(atual));
        ficha = fichario.get(atual);        
        entradanome.setText(ficha.nome);
        entradaendereco.setText(ficha.endereco);
        entradatelefone.setText(Integer.toString(ficha.telefone));
        entradacidade.setText(ficha.cidade);
        
    }//GEN-LAST:event_ProximoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telafornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telafornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telafornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telafornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run(){
                new Telafornecedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior;
    private javax.swing.JButton Cancela;
    private javax.swing.JButton Proximo;
    private javax.swing.JButton Salvar;
    private javax.swing.JLabel contador;
    private javax.swing.JTextField entradacidade;
    private javax.swing.JTextField entradaendereco;
    private javax.swing.JTextField entradanome;
    private javax.swing.JTextField entradatelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
