/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smartgas;

/**
 *
 * @author Usuario
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastroFornecedor = new javax.swing.JButton();
        CadastroCliente = new javax.swing.JButton();
        CadastroCompra = new javax.swing.JButton();
        CadastroFuncionario = new javax.swing.JButton();
        CadastroProduto = new javax.swing.JButton();
        CadastroVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CadastroFornecedor.setText("Cadastro Fornecedor");
        CadastroFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastroFornecedorMouseClicked(evt);
            }
        });

        CadastroCliente.setText("Cadastro Cliente");
        CadastroCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastroClienteMouseClicked(evt);
            }
        });

        CadastroCompra.setText("Cadastro Compra");
        CadastroCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastroCompraMouseClicked(evt);
            }
        });

        CadastroFuncionario.setText("Cadastro Funcionario");
        CadastroFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastroFuncionarioMouseClicked(evt);
            }
        });

        CadastroProduto.setText("Cadastro Produto");
        CadastroProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastroProdutoMouseClicked(evt);
            }
        });

        CadastroVenda.setText("Cadastro Venda");
        CadastroVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastroVendaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CadastroVenda)
                    .addComponent(CadastroProduto)
                    .addComponent(CadastroFuncionario)
                    .addComponent(CadastroCompra)
                    .addComponent(CadastroCliente)
                    .addComponent(CadastroFornecedor))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CadastroFornecedor)
                .addGap(28, 28, 28)
                .addComponent(CadastroCliente)
                .addGap(26, 26, 26)
                .addComponent(CadastroCompra)
                .addGap(18, 18, 18)
                .addComponent(CadastroFuncionario)
                .addGap(18, 18, 18)
                .addComponent(CadastroProduto)
                .addGap(27, 27, 27)
                .addComponent(CadastroVenda)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastroFornecedorMouseClicked
        // TODO add your handling code here:
        new Telafornecedor().setVisible(true);
        
    }//GEN-LAST:event_CadastroFornecedorMouseClicked

    private void CadastroClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastroClienteMouseClicked
        // TODO add your handling code here:
        new telacliente().setVisible(true);
    }//GEN-LAST:event_CadastroClienteMouseClicked

    private void CadastroCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastroCompraMouseClicked
        // TODO add your handling code here:
        new telacompra().setVisible(true);
    }//GEN-LAST:event_CadastroCompraMouseClicked

    private void CadastroFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastroFuncionarioMouseClicked
        // TODO add your handling code here:
        new TelaFuncionario().setVisible(true);
    }//GEN-LAST:event_CadastroFuncionarioMouseClicked

    private void CadastroProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastroProdutoMouseClicked
        // TODO add your handling code here:
        new telaproduto().setVisible(true);
    }//GEN-LAST:event_CadastroProdutoMouseClicked

    private void CadastroVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastroVendaMouseClicked
        // TODO add your handling code here:
        new telavenda().setVisible(true);
    }//GEN-LAST:event_CadastroVendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroCliente;
    private javax.swing.JButton CadastroCompra;
    private javax.swing.JButton CadastroFornecedor;
    private javax.swing.JButton CadastroFuncionario;
    private javax.swing.JButton CadastroProduto;
    private javax.swing.JButton CadastroVenda;
    // End of variables declaration//GEN-END:variables
}
